LAT_KEY = "lat"
LON_KEY = "lon"
PATENT_KEY = "patent"
TIMESTAMP_KEY = "timestamp"
TEMPERATURE_KEY = "temperature"
DRIVER_KEY = "driver"
COMMUNE_KEY = "commune"
CAPACITY_KEY = "capacity"
M_LAT_KEY = "mLat"
M_LON_KEY = "mLon"
VELOCITY_KEY = "velocity"
TRUCK_ID_KEY = "truckId"
TIME_KEY = "time"
TIME_START_KEY = "timeStart"
TIME_STOP_KEY = "timeStop"
RADIUS_KEY = "radius"
START_STOP_KEY = "startStop"
DATE_NUM_KEY = "dateNum"
CONSTRAINT_KEY = "constraint"
DATE_KEY = "date"

TRUCK_POINTS_KEY = "truckPoints"
TRUCKS_KEY = "trucks"
TRUCKS_DB_KEY = "trucks"
COMPUTED_DB_KEY = "computed"
TRUCK_DATE_COMBOS_KEY = "truckDateCombos"
POINTS_KEY = "points"
POINT_KEY = "point"
AVAILABILITY_KEY = "availability"
TRUCK_DATES_KEY = "truckDates"
ROUTE_CENTERS_KEY = "routeCenters"
CHILE_DATA_DB_KEY = "chileData"
CHILE_MAP_DB_KEY = "chileMap"
WATTS_DATA_DB_KEY = "wattsData"

#import_train
TRAINING_DB_KEY = "training"
TRAIN_DB_KEY = "train"
ROAD_DB_KEY = "roads"
INPUT_KEY = "input"
OUTPUT_KEY = "output"
FILE_NUM_KEY = "fileNum"
EDGE_ID_KEY = "edgeId"
CONF_KEY = "conf"
ID_KEY = "id"

FOR_NEIGHBORS_KEY = "forNeighbors"
BACK_NEIGHBORS_KEY = "backNeighbors"
GRAPH_KEY = "graph"
DIRECTION_KEY = "direction"
REVERSE_KEY = "reverse"
FORWARD_KEY = "forward"
BACKWARD_KEY = "backward"
NODES_KEY = "nodes"
EDGES_KEY = "edges"
START_NODE_KEY = "startNodeId"
END_NODE_KEY = "endNodeId"
COST_KEY = "cost"
START_LAT_KEY = "startLat"
START_LON_KEY = "startLon"
END_LAT_KEY = "endLat"
END_LON_KEY = "endLon"
COMPUTED_KEY = "computed"
START_POINT_KEY = "startPoint"
END_POINT_KEY = "endPoint"
CANDIDATE_KEY = "candidate"
INPUT_ID_KEY = 'inputId'

MINI_EDGES_KEY = "miniEdges"
MINI_NODES_KEY = "miniNodes"
NODE_EDGES_KEY = "nodeEdges"
LENGTH_KEY = "length"

CELL_ID_KEY = "cellId"
CELLS_KEY = "cells"
_ID_KEY = "_id"
YO_KEY = "_id"
MAX_DEGREE_KEY = "maxDegree"
KEY = "key"
VALUE_KEY = "value"

GRID_INDEXES_KEY = "gridIndexes"

START_NUM_KEY = "startNum"
END_NUM_KEY = "endNum"
END_KEY = "end"
START_KEY = "start"
NODE_ID_KEY = "nodeId"
NODE_DB_ID_KEY = "node_id"

EDGE_ID_KEY = "edgeId"
EDGE_DB_ID_KEY = 'edge_id'

SEGMENT_ID_KEY = "segmentId"
SEGMENT_DB_ID_KEY = 'segment_id'

START_EDGES_KEY = "startEdges"
END_EDGES_KEY = "endEdges"
BIG_DATA_DB_KEY = "bigData"
OSM_GRAPH_KEY = "osmGraph"

MIN_LAT_KEY = "minLat"
MIN_LON_KEY = "minLon"
MAX_LAT_KEY = "maxLat"
MAX_LON_KEY = "maxLon"
MAX_MINS_KEY = "maxMins"
CELL_IDS_KEY = "cellIds"
MINI_EDGE_CELL_IDS_KEY = "miniEdgeCellIds"
START_MINI_NODE_ID_KEY = "startMiniNodeId"
END_MINI_NODE_ID_KEY = "endMiniNodeId"
REMAINING_KEY = "remaining"

DB_KEY = "db"
DB_ID_KEY = "dbId"
MONGO_ID_KEY = "_id"
ITEM_KEY = "item"

DISTANCE_KEY = "distance"
PRIORITY_KEY = "priority"
MARKED_KEY = "marked"
HEAP_ID_KEY = "heapId"
VISITED_KEY = "visited"
DESCRIPTION_KEY = "description"
STATE_KEY = "state"
TEST_EDGES_KEY = "testEdges"
TEST_NODES_KEY = "testNodes"

STOPS_KEY = "stops"
STOP_PROPS_KEY = "stopProps"
STOP_PROP_ID_KEY = "stopPropId"
DURATION_KEY = "duration"

TOO_BIG = 16000000
CELL_SIZE = 50
MONTH_NUM = 31