/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Insights Endpoint
         * @description Compute mobility insights for a batch of GPS coordinates.
         *
         *     Accepts either a structured ``points`` array (fast path) or raw ``text``
         *     that the server will parse using :func:`bhulan.analytics.parsers.parse_any`.
         *     Setting ``options.geocode_stops = true`` enriches each detected stop
         *     with a Nominatim-derived ``place_name`` (adds ~1s per unique stop).
         */
        post: operations["insights_endpoint_v1_insights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/parse/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse File Endpoint
         * @description Parse an uploaded GPS file and return normalized points.
         *
         *     Dispatches on the filename extension: ``.gpx`` → gpxpy, ``.kml`` →
         *     stdlib XML, ``.fit`` → fitdecode, anything else → the text parsers.
         *     Files over ``MAX_UPLOAD_BYTES`` are rejected; the content is read into
         *     memory once and parsed synchronously (parsing is CPU-bound and fast
         *     enough that pushing it to a threadpool isn't worth it at this scale).
         */
        post: operations["parse_file_endpoint_v1_parse_file_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/plot/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plot Validate Endpoint
         * @description Parse and validate coordinates for the map view.
         *
         *     Returns the cleaned points plus counts of accepted and rejected rows so
         *     the frontend can show a short summary alongside the rendered track.
         */
        post: operations["plot_validate_endpoint_v1_plot_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare Endpoint
         * @description Compare 2+ tracks side by side.
         *
         *     Applies the same ``options`` to every track so users don't have to
         *     tune knobs per-track. The response is a list of per-track reports
         *     plus a pooled-hotspot list so the UI can render "shared places"
         *     separately from per-track breakdowns.
         */
        post: operations["compare_endpoint_v1_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness probe that doesn't touch Mongo.
         *
         *     Used by Docker / uptime monitors to decide whether the process is up —
         *     ``/health/ready`` still exists for the ingestion subsystem's DB check.
         */
        get: operations["healthz_v1_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint.
         *
         *     Returns 200 if service is ready and database is accessible.
         */
        get: operations["health_check_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Get non-sensitive configuration.
         *
         *     Returns selected configuration values for debugging.
         */
        get: operations["get_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/trackpoints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ingest Trackpoints
         * @description Ingest GPS track points via webhook.
         *
         *     Accepts JSON payload with GPS data, normalizes it, and persists to database.
         *
         *     Args:
         *         payload: JSON object or array of GPS records
         *         vendor: Vendor identifier (generic, geotab, samsara)
         *         ingest_id: Optional ingestion job ID (generated if not provided)
         *         x_bhulan_mapping: Optional custom mapping JSON in header
         *
         *     Returns:
         *         NormalizationResult with accepted/rejected counts and errors
         */
        post: operations["ingest_trackpoints_ingest_trackpoints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{ingest_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job Status
         * @description Get ingestion job status and statistics.
         *
         *     Args:
         *         ingest_id: Ingestion job identifier
         *
         *     Returns:
         *         Job information including status, stats, and errors
         */
        get: operations["get_job_status_jobs__ingest_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Metrics
         * @description Get Prometheus-compatible metrics.
         *
         *     Returns basic metrics about ingestion operations.
         */
        get: operations["get_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BBox */
        BBox: {
            /** Min Lat */
            min_lat: number;
            /** Min Lon */
            min_lon: number;
            /** Max Lat */
            max_lat: number;
            /** Max Lon */
            max_lon: number;
        };
        /** Body_parse_file_endpoint_v1_parse_file_post */
        Body_parse_file_endpoint_v1_parse_file_post: {
            /**
             * File
             * Format: binary
             * @description GPX, KML, FIT, CSV, JSON, or plain-text coordinates
             */
            file: string;
        };
        /**
         * CompareRequest
         * @description Request body for :func:`compare_endpoint`.
         */
        CompareRequest: {
            /**
             * Tracks
             * @description 2+ tracks to compare
             */
            tracks: components["schemas"]["CompareTrack"][];
            options?: components["schemas"]["InsightsOptions"];
        };
        /**
         * CompareResponse
         * @description Top-level compare response.
         */
        CompareResponse: {
            /** Tracks */
            tracks: components["schemas"]["CompareTrackResult"][];
            /**
             * Shared Hotspots
             * @description Hotspots computed across all tracks' pooled samples.
             */
            shared_hotspots?: components["schemas"]["HotspotOut"][];
        };
        /**
         * CompareTrack
         * @description One input track for ``POST /v1/compare``.
         */
        CompareTrack: {
            /**
             * Label
             * @description Short human-readable name (e.g. 'Monday run'). Optional.
             */
            label?: string | null;
            /**
             * Points
             * @description Pre-structured points (preferred when the client can parse).
             */
            points?: components["schemas"]["PointIn"][] | null;
            /**
             * Text
             * @description Raw coordinates (CSV, JSON, GeoJSON, or lat/lon lines).
             */
            text?: string | null;
        };
        /**
         * CompareTrackResult
         * @description Per-track slice of the compare response.
         */
        CompareTrackResult: {
            /**
             * Label
             * @description Either the caller-supplied label or a generated one
             */
            label: string;
            report: components["schemas"]["InsightsReport"];
            /**
             * Points
             * @description Normalized points for this track, ready to drop onto a map.
             */
            points?: components["schemas"]["PointIn"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HotspotOut
         * @description One detected density cluster.
         *
         *     ``time_spent_min`` is ``None`` when the input has no timestamps —
         *     we can still identify the hotspot geographically, we just can't
         *     say how long was spent there.
         */
        HotspotOut: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Sample Count */
            sample_count: number;
            /** Visit Count */
            visit_count: number;
            /** Time Spent Min */
            time_spent_min: number | null;
            /** First Ts */
            first_ts: string | null;
            /** Last Ts */
            last_ts: string | null;
            /**
             * Place Name
             * @description Reverse-geocoded label for the centroid. Only populated when InsightsOptions.geocode_stops is true.
             */
            place_name?: string | null;
        };
        /**
         * InsightsOptions
         * @description Tunables for the insights pipeline.
         */
        InsightsOptions: {
            /**
             * Stop Radius M
             * @default 50
             */
            stop_radius_m: number;
            /**
             * Min Stop Minutes
             * @description Minutes
             * @default 5
             */
            min_stop_minutes: number;
            /**
             * Moving Speed Kmh
             * @description Speed threshold for 'moving'
             * @default 3.6
             */
            moving_speed_kmh: number;
            /**
             * Merge Stops Within M
             * @description If set, merge consecutive stops whose centroids are within this radius
             */
            merge_stops_within_m?: number | null;
            /**
             * Geocode Stops
             * @description If true, reverse-geocode each stop's centroid via Nominatim and populate StopOut.place_name. Respects Nominatim's 1 req/sec limit; expect +N seconds latency for N unique stops.
             * @default false
             */
            geocode_stops: boolean;
            /**
             * Trip Split Stop Minutes
             * @description Stops longer than this end the current trip and start a new one. Shorter stops stay inside the trip they happen during.
             * @default 30
             */
            trip_split_stop_minutes: number;
            /**
             * Trip Split Gap Minutes
             * @description A gap between consecutive samples longer than this ends the current trip (device-off or missing data).
             * @default 60
             */
            trip_split_gap_minutes: number;
            /**
             * Hotspot Grid M
             * @description Grid cell size (meters) used for hotspot clustering.
             * @default 100
             */
            hotspot_grid_m: number;
            /**
             * Hotspot Min Samples
             * @description Minimum samples per grid cell to qualify as a hotspot.
             * @default 5
             */
            hotspot_min_samples: number;
            /**
             * Hotspot Max Results
             * @description Maximum number of hotspots returned, sorted by sample count desc.
             * @default 10
             */
            hotspot_max_results: number;
        };
        /** InsightsQuality */
        InsightsQuality: {
            /**
             * Rejected Points
             * @default 0
             */
            rejected_points: number;
            /** Issues */
            issues?: string[];
        };
        /** InsightsReport */
        InsightsReport: {
            summary: components["schemas"]["InsightsSummary"];
            /** Stops */
            stops: components["schemas"]["StopOut"][];
            /** Segments */
            segments: components["schemas"]["SegmentOut"][];
            /** Trips */
            trips?: components["schemas"]["TripOut"][];
            /** Hotspots */
            hotspots?: components["schemas"]["HotspotOut"][];
            quality: components["schemas"]["InsightsQuality"];
        };
        /** InsightsSummary */
        InsightsSummary: {
            /** Point Count */
            point_count: number;
            /** Accepted Point Count */
            accepted_point_count: number;
            time_range: components["schemas"]["TimeRange"] | null;
            /** Total Distance Km */
            total_distance_km: number;
            /** Moving Time Min */
            moving_time_min: number;
            /** Idle Time Min */
            idle_time_min: number;
            /** Avg Moving Speed Kmh */
            avg_moving_speed_kmh: number;
            /** Max Speed Kmh */
            max_speed_kmh: number;
            bbox: components["schemas"]["BBox"] | null;
        };
        /**
         * NormalizationResult
         * @description Result of normalizing a batch of GPS data.
         */
        NormalizationResult: {
            /**
             * Accepted
             * @description Number of records accepted
             */
            accepted: number;
            /**
             * Rejected
             * @description Number of records rejected
             */
            rejected: number;
            /**
             * Errors
             * @description Row index to error message mapping
             */
            errors?: {
                [key: string]: string;
            };
            /**
             * Ingest Id
             * @description Ingestion job ID
             */
            ingest_id: string;
        };
        /**
         * ParseFileResponse
         * @description Response for :func:`parse_file_endpoint` — the frontend feeds the
         *     accepted points straight into ``/v1/insights`` or ``/v1/plot/validate``.
         */
        ParseFileResponse: {
            /** Filename */
            filename: string;
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Issues */
            issues: string[];
            /** Points */
            points: components["schemas"]["PointIn"][];
        };
        /**
         * PlotRequest
         * @description Request for :func:`plot_validate` — either structured points or raw text.
         */
        PlotRequest: {
            /**
             * Points
             * @description Pre-structured points (preferred when the client can parse)
             */
            points?: components["schemas"]["PointIn"][] | null;
            /**
             * Text
             * @description Raw user-pasted text: CSV, JSON, GeoJSON, or lat/lon lines
             */
            text?: string | null;
        };
        /**
         * PlotResponse
         * @description Normalized points the frontend can drop straight onto a map.
         */
        PlotResponse: {
            /** Accepted */
            accepted: number;
            /** Rejected */
            rejected: number;
            /** Issues */
            issues: string[];
            /** Points */
            points: components["schemas"]["PointIn"][];
        };
        /**
         * PointIn
         * @description One GPS sample as it arrives over the wire.
         */
        PointIn: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Ts Utc
             * @description Timestamp in UTC; required for any time-based insight
             */
            ts_utc?: string | null;
            /**
             * Speed Mps
             * @description Optional device-reported speed
             */
            speed_mps?: number | null;
        };
        /**
         * RawInsightsRequest
         * @description ``/v1/insights`` request that accepts pasted text in lieu of structured input.
         */
        RawInsightsRequest: {
            /** Points */
            points?: components["schemas"]["PointIn"][] | null;
            /** Text */
            text?: string | null;
            options?: components["schemas"]["InsightsOptions"];
        };
        /** SegmentOut */
        SegmentOut: {
            /** Kind */
            kind: string;
            /** Start Ts */
            start_ts: string | null;
            /** End Ts */
            end_ts: string | null;
            /** Distance Km */
            distance_km: number;
            /** Duration Min */
            duration_min: number;
            /** Avg Speed Kmh */
            avg_speed_kmh: number;
        };
        /** StopOut */
        StopOut: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /**
             * Start Ts
             * Format: date-time
             */
            start_ts: string;
            /**
             * End Ts
             * Format: date-time
             */
            end_ts: string;
            /** Duration Min */
            duration_min: number;
            /** Radius M */
            radius_m: number;
            /** Sample Count */
            sample_count: number;
            /**
             * Place Name
             * @description Reverse-geocoded label for the centroid. Only populated when InsightsOptions.geocode_stops is true; otherwise None.
             */
            place_name?: string | null;
        };
        /** TimeRange */
        TimeRange: {
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /**
         * TripOut
         * @description One detected trip with derived mobility stats.
         *
         *     Timestamps are ``None`` when the underlying samples carried none;
         *     everything else is zero-safe so the UI can render without guarding.
         */
        TripOut: {
            /**
             * Index
             * @description 0-based index of the trip in start order
             */
            index: number;
            /** Start Ts */
            start_ts: string | null;
            /** End Ts */
            end_ts: string | null;
            /** Start Lat */
            start_lat: number;
            /** Start Lon */
            start_lon: number;
            /** End Lat */
            end_lat: number;
            /** End Lon */
            end_lon: number;
            /** Distance Km */
            distance_km: number;
            /** Duration Min */
            duration_min: number;
            /** Moving Time Min */
            moving_time_min: number;
            /** Idle Time Min */
            idle_time_min: number;
            /** Max Speed Kmh */
            max_speed_kmh: number;
            /** Sample Count */
            sample_count: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    insights_endpoint_v1_insights_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RawInsightsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_file_endpoint_v1_parse_file_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_parse_file_endpoint_v1_parse_file_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ParseFileResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plot_validate_endpoint_v1_plot_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlotRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlotResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_endpoint_v1_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_v1_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    health_check_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    ingest_trackpoints_ingest_trackpoints_post: {
        parameters: {
            query?: {
                /** @description Vendor/source identifier */
                vendor?: string;
                /** @description Ingestion job ID */
                ingest_id?: string | null;
            };
            header?: {
                /** @description Custom mapping JSON */
                "x-bhulan-mapping"?: string | null;
                "x-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                }[] | {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NormalizationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_status_jobs__ingest_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ingest_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
